'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
type CropBox = [number,number,number,number];
type Product = {id:string;name:string;en:string;category:string;box:CropBox;alt?:CropBox};
const products:Product[]=[
{id:'silk-scarf',name:'실크 스카프',en:'SILK SCARF',category:'스카프',box:[28,450,108,247]},
{id:'card-holder',name:'카드 지갑',en:'CARD HOLDER',category:'지갑 & 파우치',box:[168,492,131,98],alt:[168,597,131,87]},
{id:'mini-pouch',name:'미니 파우치',en:'MINI POUCH',category:'지갑 & 파우치',box:[321,587,126,100],alt:[316,469,143,112]},
{id:'iphone17',name:'아이폰 17 에어 케이스',en:'iPHONE 17 AIR CASE',category:'디지털 액세서리',box:[493,472,90,220]},
{id:'iphone18',name:'아이폰 18 케이스',en:'iPHONE 18 CASE',category:'디지털 액세서리',box:[643,480,97,208]},
{id:'airpods',name:'에어팟 케이스',en:'AIRPODS CASE',category:'디지털 액세서리',box:[783,479,108,103],alt:[782,590,110,99]},
{id:'ipad',name:'아이패드 케이스',en:'iPAD CASE',category:'디지털 액세서리',box:[942,473,139,218]},
{id:'macbook',name:'맥북 프로 슬리브',en:'MACBOOK PRO SLEEVE',category:'디지털 액세서리',box:[1100,527,185,136]},
];
function Icon({name}:{name:'menu'|'search'|'heart'|'bag'|'close'|'arrow'}){const paths={menu:<><path d="M3 7h18M3 17h18"/></>,search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,heart:<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 6l-1.1-1.2a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>,bag:<><path d="M5 7h14l2 14H3L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></>,close:<path d="m5 5 14 14M19 5 5 19"/>,arrow:<path d="M3 12h18m-7-7 7 7-7 7"/>};return <svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function Crop({box,alt,className='',source='maison'}:{box:CropBox;alt:string;className?:string;source?:'maison'|'music'}){const [x,y,w,h]=box;const [iw,ih]=source==='maison'?[1312,1199]:[1024,572];return <div className={`crop ${className}`} style={{aspectRatio:`${w}/${h}`, '--crop-ratio':w/h} as CSSProperties}><img src={`/images/${source==='maison'?'maison-board.png':'music-board.jpg'}`} alt={alt} style={{width:`${iw/w*100}%`,height:'auto',left:`${-x/w*100}%`,top:0,transform:`translateY(${-y/ih*100}%)`}} draggable={false}/></div>}
export default function Home(){
 const [panel,setPanel]=useState<'menu'|'search'|'saved'|'bag'|'product'|null>(null);
 const [chosen,setChosen]=useState<Product>(products[0]);
 const [category,setCategory]=useState('전체');
 const [query,setQuery]=useState('');
 const [saved,setSaved]=useState<string[]>([]);
 const [variant,setVariant]=useState(false);
 const [storageMessage,setStorageMessage]=useState('');
 const modal=useRef<HTMLDialogElement>(null);
 const searchInput=useRef<HTMLInputElement>(null);
 const returnFocus=useRef<HTMLElement|null>(null);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('belior-maison-favourites')||'[]');if(Array.isArray(s))setSaved(s.filter((id:unknown)=>typeof id==='string'&&products.some(p=>p.id===id)));}catch{}},[]);
 function open(next:NonNullable<typeof panel>,p?:Product){returnFocus.current=document.activeElement as HTMLElement;setPanel(next);if(p){setChosen(p);setVariant(false)}modal.current?.showModal();if(next==='search')setTimeout(()=>searchInput.current?.focus(),0)}
 function close(){modal.current?.close();setPanel(null);returnFocus.current?.focus()}
 function favourite(id:string){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);try{localStorage.setItem('belior-maison-favourites',JSON.stringify(next));setStorageMessage('')}catch{setStorageMessage('브라우저 저장이 제한되어 이번 방문 중에만 보관됩니다.')}}
 function chooseCategory(c:string){setCategory(c);setQuery('');close();setTimeout(()=>document.getElementById('collections')?.scrollIntoView({behavior:'smooth'}),0)}
 const filtered=products.filter(p=>(category==='전체'||p.category===category)&&`${p.name} ${p.en}`.toLowerCase().includes(query.toLowerCase()));
 function card(p:Product){return <article className="product" key={p.id}><div className="product-photo"><button className="product-open" onClick={()=>open('product',p)} aria-label={`${p.name} 상세 보기`}><Crop box={p.box} alt={`BELiOR ${p.name} 콘셉트`} className={p.id==='silk-scarf'?'scarf-crop':''}/></button><button className={`save ${saved.includes(p.id)?'active':''}`} aria-label={`${p.name} ${saved.includes(p.id)?'관심 목록에서 삭제':'관심 목록에 저장'}`} aria-pressed={saved.includes(p.id)} onClick={()=>favourite(p.id)}><Icon name="heart"/></button></div><div className="product-info"><button onClick={()=>open('product',p)}><h3>{p.name}</h3><p>{p.en}</p></button><span>컬렉션 프리뷰</span></div></article>}
 return <><a className="skip" href="#main">본문 바로가기</a><div className="topline">MUSIC ART PEOPLE — A BRIGHTER TOMORROW</div>
 <header className="header"><div className="header-left"><button onClick={()=>open('menu')} aria-label="메뉴 열기"><Icon name="menu"/><span>메뉴</span></button><button onClick={()=>open('search')} aria-label="컬렉션 검색"><Icon name="search"/><span>검색</span></button></div><a className="wordmark" href="#main" aria-label="BELiOR 홈">BELiOR</a><div className="header-right"><button onClick={()=>open('saved')} aria-label={`관심 목록 ${saved.length}개`}><Icon name="heart"/>{saved.length>0&&<span className="count">{saved.length}</span>}</button><button onClick={()=>open('bag')} aria-label="쇼핑백 열기"><Icon name="bag"/></button></div></header>
 <nav className="quick-nav" aria-label="컬렉션 메뉴"><a href="#collections" onClick={()=>{setCategory('전체');setQuery('')}}>메종 컬렉션</a><a href="#collections" onClick={()=>{setCategory('스카프');setQuery('')}}>스카프</a><a href="#collections" onClick={()=>{setCategory('지갑 & 파우치');setQuery('')}}>지갑 & 파우치</a><a href="#collections" onClick={()=>{setCategory('디지털 액세서리');setQuery('')}}>디지털 액세서리</a><a href="#house">BELiOR 하우스</a></nav>
 <main id="main"><section className="hero" aria-labelledby="hero-title"><div className="campaign"><Crop box={[0,0,720,385]} alt="BELiOR 블랙 가죽 소품과 실크 스카프 메종 컬렉션 콘셉트"/><span className="concept-label">COLLECTION CONCEPT</span></div><div className="hero-caption"><p className="eyebrow">BELiOR</p><h1 id="hero-title">MAISON COLLECTION</h1><p className="hero-korean">일상이, 더 아름다워지는 순간.</p><a className="underline-link" href="#collections">컬렉션 살펴보기</a></div></section>
 <section className="catalog" id="collections"><div className="section-heading"><h2>컬렉션</h2><p>OBJECTS FOR A MORE BEAUTIFUL TOMORROW.</p></div><div className="catalog-toolbar"><div className="filters" role="group" aria-label="컬렉션 필터">{['전체','스카프','지갑 & 파우치','디지털 액세서리'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><span className="result-count" aria-live="polite">{filtered.length}개</span></div>{query&&<div className="search-status">“{query}” 검색 결과 <button onClick={()=>setQuery('')}>검색 해제 ×</button></div>}<div className="product-grid">{filtered.map(card)}</div>{filtered.length===0&&<div className="empty"><h3>일치하는 컬렉션이 없습니다.</h3><button className="outline-button" onClick={()=>{setCategory('전체');setQuery('')}}>전체 컬렉션 보기</button></div>}<p className="catalog-note">제공된 디자인 콘셉트 이미지입니다. 판매 상품·가격·출시 일정은 아직 확정되지 않았습니다.</p></section>
 <section className="editorial" id="house"><div className="editorial-photo"><Crop box={[0,0,404,286]} source="music" alt="BELiOR 하우스와 음악 조각 콘셉트"/></div><div className="editorial-copy"><img src="/images/belior-symbol.png" alt="BELiOR 심볼" width="42" height="63"/><p className="eyebrow">THE ART OF EVERYDAY</p><h2>A MORE BEAUTIFUL.<br/><em>EVERYDAY.</em></h2><p>일상이, 더 아름다워지는 순간.</p><a className="underline-link" href="#collections">메종 컬렉션 보기</a></div></section>
 <section className="music"><div className="music-visual"><Crop box={[404,142,365,145]} source="music" alt="BELiOR 야외 현악 앙상블 콘셉트 이미지"/></div><div className="music-copy"><p className="eyebrow">MUSIC · ART · PEOPLE</p><h2>THE WORLD OF BELiOR</h2><a className="underline-link" href="https://belior-twottiva-house.jwjsqckczh.chatgpt.site" target="_blank" rel="noopener noreferrer">Music House 살펴보기 ↗</a></div></section>
 </main><footer><div className="footer-top"><a className="footer-wordmark" href="#main">BELiOR</a><p>MUSIC ART PEOPLE<br/>A BRIGHTER TOMORROW</p><nav aria-label="하단 메뉴"><a href="#collections">컬렉션</a><a href="#house">BELiOR 하우스</a><button onClick={()=>open('bag')}>온라인 구매 안내</button></nav></div><div className="footer-bottom"><span>MAISON COLLECTION · WEBSITE CONCEPT</span><span>belior.co.kr을 위한 웹사이트 시안</span><a href="#main">맨 위로 ↑</a></div></footer>
 <dialog ref={modal} className={`panel ${panel==='product'?'product-dialog':''}`} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}} aria-labelledby="panel-title"><div className="panel-top"><h2 id="panel-title">{panel==='menu'?'BELiOR':panel==='search'?'컬렉션 검색':panel==='saved'?'관심 목록':panel==='bag'?'쇼핑백':chosen.name}</h2><button onClick={close} aria-label="닫기"><Icon name="close"/></button></div>
 {panel==='menu'&&<div className="menu-content"><p className="eyebrow">MAISON COLLECTION</p>{['전체','스카프','지갑 & 파우치','디지털 액세서리'].map(c=><button key={c} onClick={()=>chooseCategory(c)}>{c==='전체'?'전체 컬렉션':c}<Icon name="arrow"/></button>)}<a href="#house" onClick={close}>BELiOR 하우스</a><a href="https://belior-twottiva-house.jwjsqckczh.chatgpt.site" target="_blank" rel="noopener noreferrer">Music House ↗</a><Crop box={[0,0,720,385]} alt="BELiOR 메종 컬렉션 콘셉트"/></div>}
 {panel==='search'&&<div className="search-content"><form onSubmit={e=>{e.preventDefault();setCategory('전체');close();setTimeout(()=>document.getElementById('collections')?.scrollIntoView(),0)}}><label htmlFor="query">찾고 싶은 컬렉션</label><div className="search-field"><input ref={searchInput} id="query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="스카프, 카드 지갑, 케이스" type="search"/><button aria-label="검색 결과 보기" type="submit"><Icon name="search"/></button></div></form><p className="eyebrow">컬렉션 바로가기</p>{products.filter(p=>`${p.name} ${p.en}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className="search-result" key={p.id} onClick={()=>{setChosen(p);setVariant(false);setPanel('product')}}>{p.name}<Icon name="arrow"/></button>)}{!products.some(p=>`${p.name} ${p.en}`.toLowerCase().includes(query.toLowerCase()))&&<p>일치하는 컬렉션이 없습니다.</p>}</div>}
 {panel==='saved'&&<div className="saved-content">{saved.length?<><p>이 브라우저에 보관한 컬렉션입니다.</p><div className="saved-grid">{products.filter(p=>saved.includes(p.id)).map(card)}</div></>:<div className="empty"><Icon name="heart"/><h3>아직 저장한 컬렉션이 없습니다.</h3><p>마음에 드는 제품의 하트를 눌러 보관하세요.</p><button className="outline-button" onClick={()=>chooseCategory('전체')}>컬렉션 살펴보기</button></div>}{storageMessage&&<p role="status">{storageMessage}</p>}</div>}
 {panel==='bag'&&<div className="empty"><Icon name="bag"/><h3>온라인 부티크 준비 중</h3><p>현재는 디자인 콘셉트를 살펴보는 컬렉션 프리뷰입니다.<br/>판매 가격과 상품 정보가 확정되면 구매 기능을 연결합니다.</p><button className="outline-button" onClick={()=>chooseCategory('전체')}>컬렉션 살펴보기</button></div>}
 {panel==='product'&&<div className="detail"><div className="detail-photo"><Crop box={variant&&chosen.alt?chosen.alt:chosen.box} alt={`${chosen.name} 디자인 콘셉트`} className={chosen.id==='silk-scarf'?'scarf-crop':''}/></div><div className="detail-copy"><p className="eyebrow">MAISON COLLECTION</p><h3>{chosen.name}</h3><p className="english-name">{chosen.en}</p>{chosen.alt&&<div className="variants" role="group" aria-label="디자인 이미지 선택"><button className={!variant?'selected':''} onClick={()=>setVariant(false)} aria-pressed={!variant}>블랙</button><button className={variant?'selected':''} onClick={()=>setVariant(true)} aria-pressed={variant}>{chosen.id==='airpods'?'아이보리':'패턴'}</button></div>}<p className="detail-description">첨부된 BELiOR 디자인 콘셉트입니다.<br/>실제 판매 상품과 사양은 확정되지 않았습니다.</p><button className="outline-button" onClick={()=>favourite(chosen.id)}><Icon name="heart"/>{saved.includes(chosen.id)?'관심 목록에서 삭제':'관심 목록에 저장'}</button><div className="purchase-note"><strong>온라인 구매 준비 중</strong><p>판매 가격·재고·출시 일정 미정</p></div></div></div>}
 </dialog></>;
}
